# Generated by Django 5.0.4 on 2024-04-19 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.FilePathField(path='/var/folders/b2/2vl598v93fl44j8bgflhd4rm0000gp/T')),
                ('deadline', models.DateTimeField()),
                ('served_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
