# Generated by Django 5.0.4 on 2024-04-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animation',
            old_name='deadline',
            new_name='start_time',
        ),
    ]
