# Generated by Django 5.0.4 on 2024-04-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
