# Generated by Django 5.0.4 on 2024-04-20 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_animation_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='file_path',
            field=models.FilePathField(blank=True, null=True, path='render'),
        ),
        migrations.AlterField(
            model_name='animation',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 21, 9, 35, 385725, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
